import { getServerSession } from "next-auth";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession();
  console.log(`--- Session --- : ${JSON.stringify(session, null, 2)}`);
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  )
}
