import { LogoutFunction } from "@/components/auth/Logout";
import { getServerSession } from "next-auth"
import { json } from "stream/consumers";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body>
        {!! session &&
        <nav>
          <LogoutFunction/>
        </nav> }
        {children}
      </body>
    </html>
  )
}
