import type { Metadata } from "next";
import "./globals.css";
import { Header } from "@/components/header/HeaderTab";
import { Footer } from "@/components/footer/FooterTab";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="root">
            <Header />
            {children}
            <Footer />
        </div>
      </body>
    </html>
  );
}
