import type { Metadata } from "next";
import "./globals.css";
import { Header } from "@/components/header/HeaderTab";
import { Content } from "@/components/content/Content";
import { Footer } from "@/components/footer/FooterTab";
import Head from "next/head";
import { RecoilRoot } from "recoil";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="root">
            <Header />
            {children}
            <Footer />
        </div>
      </body>
    </html>
  );
}
